-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.autobusy
(
    id_bus integer[] NOT NULL,
    rejestracja character varying(10)[] NOT NULL,
    marka character varying(50)[] NOT NULL,
    sprawnosc boolean[] NOT NULL,
    rodzaj integer[] NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY (id_bus)
);

CREATE TABLE IF NOT EXISTS public.uzytkownicy
(
    id_uzytkownik integer[] NOT NULL,
    imie character varying(30)[],
    nazwisko character varying(30)[],
    id_stanowisko integer[] NOT NULL,
    PRIMARY KEY (id_uzytkownik)
);

CREATE TABLE IF NOT EXISTS public.typ_stanowiska
(
    "id_typStanowiska" integer[] NOT NULL,
    nazwa_stanowiska character varying(50) NOT NULL,
    PRIMARY KEY ("id_typStanowiska")
);

CREATE TABLE IF NOT EXISTS public.rodzaj_autobusu
(
    id_rodzaj integer[] NOT NULL,
    "nazwaRodzaj" character varying(50)[] NOT NULL,
    PRIMARY KEY (id_rodzaj)
);

CREATE TABLE IF NOT EXISTS public.rodzaj_zmiany
(
    id_rzmiany integer[] NOT NULL,
    nr_zmiany integer[] NOT NULL,
    g_rozp time without time zone NOT NULL,
    g_zakon time without time zone NOT NULL,
    PRIMARY KEY (id_rzmiany)
);

CREATE TABLE IF NOT EXISTS public.dni_tygodnia
(
    id_dnityg integer[] NOT NULL,
    dzien character varying(25)[] NOT NULL,
    PRIMARY KEY (id_dnityg)
);

CREATE TABLE IF NOT EXISTS public.dostepnosci_kierowcow
(
    "id_dostKier" integer[] NOT NULL,
    id_uzytk integer[] NOT NULL,
    dzien_tyg integer[] NOT NULL,
    rodzaj_zmiany integer[] NOT NULL,
    CONSTRAINT "dostKierowcy" PRIMARY KEY ("id_dostKier")
);

CREATE TABLE IF NOT EXISTS public.przystanki
(
    id_przystanku integer[] NOT NULL,
    "nazwaPrzystanku" character varying(35)[] NOT NULL,
    PRIMARY KEY (id_przystanku)
);

CREATE TABLE IF NOT EXISTS public."Linia"
(
    id_linii integer[] NOT NULL,
    "nazwaLinii" character varying(10)[] NOT NULL,
    trasa_przystankow integer[] NOT NULL,
    tryb_kurs integer[] NOT NULL,
    PRIMARY KEY (id_linii)
);

CREATE TABLE IF NOT EXISTS public."przystanekwLinii"
(
    "id_przystLin" integer[] NOT NULL,
    ennum integer[] NOT NULL,
    PRIMARY KEY ("id_przystLin")
);

CREATE TABLE IF NOT EXISTS public.kurs_realizacja
(
    id_realizacji integer[] NOT NULL,
    "nazwaLini_rel" integer[] NOT NULL,
    dzien_rel integer[] NOT NULL,
    "rodZmian" integer[] NOT NULL,
    "id_kierowcyRel" integer[] NOT NULL,
    "id_busuRel" integer[] NOT NULL,
    godz_start integer[] NOT NULL,
    PRIMARY KEY (id_realizacji)
);

CREATE TABLE IF NOT EXISTS public.czasowo_przyst
(
    id_czasods integer[] NOT NULL,
    enum_czasods "char" NOT NULL,
    PRIMARY KEY (id_czasods)
);

CREATE TABLE IF NOT EXISTS public.czas_przyjazdy
(
    "id_czPrzyjazdy" integer[] NOT NULL,
    "przystlincczPrz" integer[] NOT NULL,
    "czasodsczPrz" integer[] NOT NULL,
    PRIMARY KEY ("id_czPrzyjazdy")
);

CREATE TABLE IF NOT EXISTS public.kurs
(
    id_kurs integer[] NOT NULL,
    "nazwaLini_k" integer[] NOT NULL,
    rodzaj_bus integer[] NOT NULL,
    trasa_k integer[] NOT NULL,
    czas_przyjazdu integer[] NOT NULL,
    PRIMARY KEY (id_kurs)
);

CREATE TABLE IF NOT EXISTS public.tryb_kutsowania
(
    id_tryb integer[] NOT NULL,
    nazwa_trybu character varying(30)[] NOT NULL,
    PRIMARY KEY (id_tryb)
);

ALTER TABLE IF EXISTS public.autobusy
    ADD CONSTRAINT rodzaj FOREIGN KEY (rodzaj)
    REFERENCES public.rodzaj_autobusu (id_rodzaj) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.uzytkownicy
    ADD CONSTRAINT id_stanowisko FOREIGN KEY (id_stanowisko)
    REFERENCES public.typ_stanowiska ("id_typStanowiska") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dostepnosci_kierowcow
    ADD CONSTRAINT "dzienTyg" FOREIGN KEY (dzien_tyg)
    REFERENCES public.dni_tygodnia (id_dnityg) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dostepnosci_kierowcow
    ADD CONSTRAINT "rodzajZmiany" FOREIGN KEY (rodzaj_zmiany)
    REFERENCES public.rodzaj_zmiany (id_rzmiany) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dostepnosci_kierowcow
    ADD CONSTRAINT "idUzytk" FOREIGN KEY (id_uzytk)
    REFERENCES public.uzytkownicy (id_uzytkownik) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Linia"
    ADD CONSTRAINT "trasaP" FOREIGN KEY (trasa_przystankow)
    REFERENCES public."przystanekwLinii" ("id_przystLin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Linia"
    ADD CONSTRAINT "trybKur" FOREIGN KEY (tryb_kurs)
    REFERENCES public.tryb_kutsowania (id_tryb) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."przystanekwLinii"
    ADD CONSTRAINT "przystankiE" FOREIGN KEY (ennum)
    REFERENCES public.przystanki (id_przystanku) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs_realizacja
    ADD CONSTRAINT nazwa_l FOREIGN KEY ("nazwaLini_rel")
    REFERENCES public."Linia" (id_linii) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs_realizacja
    ADD CONSTRAINT dzien_l FOREIGN KEY (dzien_rel)
    REFERENCES public.dni_tygodnia (id_dnityg) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs_realizacja
    ADD CONSTRAINT zmiana_k FOREIGN KEY ("rodZmian")
    REFERENCES public.rodzaj_zmiany (id_rzmiany) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs_realizacja
    ADD CONSTRAINT bus_k FOREIGN KEY ("id_busuRel")
    REFERENCES public.autobusy (id_bus) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs_realizacja
    ADD CONSTRAINT "godzStart_k" FOREIGN KEY (godz_start)
    REFERENCES public.czas_przyjazdy ("id_czPrzyjazdy") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs_realizacja
    ADD CONSTRAINT kierowcy FOREIGN KEY ("id_kierowcyRel")
    REFERENCES public.dostepnosci_kierowcow ("id_dostKier") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.czas_przyjazdy
    ADD CONSTRAINT przystanki FOREIGN KEY ("przystlincczPrz")
    REFERENCES public."przystanekwLinii" ("id_przystLin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.czas_przyjazdy
    ADD CONSTRAINT czasods FOREIGN KEY ("czasodsczPrz")
    REFERENCES public.czasowo_przyst (id_czasods) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs
    ADD CONSTRAINT trasa_kk FOREIGN KEY (trasa_k)
    REFERENCES public."przystanekwLinii" ("id_przystLin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs
    ADD CONSTRAINT "czasPrz" FOREIGN KEY (czas_przyjazdu)
    REFERENCES public.czas_przyjazdy ("id_czPrzyjazdy") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kurs
    ADD CONSTRAINT "nazwaLiniii" FOREIGN KEY ("nazwaLini_k")
    REFERENCES public."Linia" (id_linii) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;